services:
  toxic-bet-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toxic-bet-fe
    restart: unless-stopped
    ports:
      - "4200:4000"
    networks:
      - shared-services

networks:
  shared-services:
    external: true
